# Generated by Django 6.0.5 on 2026-05-14 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('num_permis', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immatriculation', models.TextField()),
                ('marque', models.TextField()),
                ('modele', models.TextField()),
                ('etat', models.TextField(choices=[('disponible', 'Disponible'), ('en mission', 'En mission'), ('en panne', 'En panne'), ('en maintenance', 'En maintenance'), ('archivé', 'Archivé')], default='disponible')),
                ('kilometrage', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('statut', models.TextField(choices=[('planifiée', 'Planifiée'), ('en cours', 'En cours'), ('terminée', 'Terminée'), ('annulée', 'Annulée')], default='planifiée')),
                ('driver', models.ForeignKey(db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.driver')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
            options={
                'db_table': 'missions',
                'managed': True,
            },
        ),
    ]
