# Generated by Django 6.0.5 on 2026-05-14 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='consommation_litres',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mission',
            name='cout_carburant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_intervention', models.TextField()),
                ('date_maintenance', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('vehicule', models.ForeignKey(db_column='vehicule_id', on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
            options={
                'db_table': 'maintenances',
                'managed': True,
            },
        ),
    ]
