# Generated by Django 6.0.5 on 2026-05-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mission_consommation_litres_mission_cout_carburant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date_assurance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_vignette',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_visite_technique',
            field=models.DateField(blank=True, null=True),
        ),
    ]
