# Generated by Django 6.0.5 on 2026-05-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehicle_date_assurance_vehicle_date_vignette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='pieces_rechange',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='prestataire_garage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mission',
            name='km_arrivee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='km_depart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='km_prochain_entretien',
            field=models.IntegerField(default=0),
        ),
    ]
