# Generated by Django 6.0.5 on 2026-05-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_maintenance_pieces_rechange_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_maintenance_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seuil_maintenance',
            field=models.IntegerField(default=10000),
        ),
    ]
