# Generated by Django 6.0.5 on 2026-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vehicle_options_vehicle_last_maintenance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='ville_arrivee',
            field=models.CharField(default='Tanger', max_length=100),
        ),
        migrations.AddField(
            model_name='mission',
            name='ville_depart',
            field=models.CharField(default='Casablanca', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(default=33.5731),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(default=-7.5898),
        ),
    ]
